{% set name = "spfft" %}
{% set version = "1.1.1" %}

{% set build = 2 %}

{% set mpi = mpi or "openmpi" %}
{% set mpi_prefix = "mpi_" + mpi %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://github.com/eth-cscs/spfft/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 675a048124a96b8c7f89d59d3ac0355833e28b38622e76c4d478ee91b25d766c

build:
  number: {{ build }}
  skip: True  # [win]

outputs:
  - name: spfft
    script: build-spfft.sh
    build:
      string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}
      run_exports:
        - {{ pin_subpackage("spfft", max_pin="x.x") }}
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ stdlib("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("fortran") }}
        - {{ mpi }}
        - cmake >=3.18
        - ninja >=1.13
        - pkg-config
      host:
        - {{ mpi }}
        - _openmp_mutex
        - "fftw * {{ mpi_prefix }}_*"
      run:
        - {{ mpi }}
        - _openmp_mutex
        - "fftw * {{ mpi_prefix }}_*"
    test:
      commands:
        - test -f "${PREFIX}/lib/libspfft${SHLIB_EXT}"
    about:
      summary: Sparse 3D FFT shared library (SpFFT)
  - name: spfft-static
    script: build-spfft.sh
    build:
      string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ stdlib("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("fortran") }}
        - {{ mpi }}
        - cmake >=3.18
        - ninja >=1.13
        - pkg-config
      host:
        - {{ mpi }}
        - _openmp_mutex
        - "fftw * {{ mpi_prefix }}_*"
      run:
        - {{ mpi }}
        - _openmp_mutex
        - "fftw * {{ mpi_prefix }}_*"
    test:
      commands:
        - test -f "${PREFIX}/lib/libspfft.a"
    about:
      summary: Sparse 3D FFT static library (SpFFT)

about:
  home: https://github.com/eth-cscs/SpFFT.git
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: SpFFT is A 3D FFT library for sparse frequency domain data written in C++ with support for MPI, OpenMP, CUDA and ROCm.
  description: |
    Inspired by the need of some computational material science applications
    with spherical cutoff data in frequency domain, SpFFT provides Fast Fourier
    Transformations of sparse frequency domain data. For distributed
    computations with MPI, slab decomposition in space domain and pencil
    decomposition in frequency domain (sparse data within a pencil / column must
    be on one rank) is used.
  doc_url: https://spfft.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/eth-cscs/SpFFT

extra:
  recipe-maintainers:
    - AdhocMan
    - mkrack
